### ISSUE TITLE
Request: Load ROM from URL parameter

### ISSUE THREAD

**Issue by BigEd** [ppeccin/javatari.js#1]
Great to see this JavaScript version. I'd like to be able to load a ROM from the original URL, like
http://javatari.org/?rom=http://atariage.com/2600/roms/SpaceInvaders.zip
or
http://javatari.org/?rom=http://www.2600online.com/games/missilecommand.bin
or similar. Is that already possible? If not, please consider this a feature request.

**Comment by ppeccin** [comment]
Unfortunately its your browser that is blocking this, because of the "Same Origin Policy". Javascript that runs on the client (which is the case for an emulator) is not allowed to actively download content from a different domain.
Will will need to place the ROMs in the same server that is serving the emulator.

Regards,
Peccin

**Comment by BigEd** [comment]
That would be great, thanks. I wonder, can you find at least one ROM which is freely distributable or acceptably licensed and include it in your main site?  (I'd like to have a link to your emulator which runs something, as opposed to one which needs something more to be found first.)  I see the Halo 2600 is freely available, but I don't know if it is freely redistributable:
http://atariage.com/forums/topic/166916-halo-for-the-2600-released-at-cge-download-the-game-here

**Comment by estivalet** [comment]
@ppeccin is this feature already implemented?

**Comment by ppeccin** [comment]
Sorry guys... I'm kinda focused lately on my other project http:\\webmsx.org

But I promise I will dedicate some time to Javatari in the next weeks. This
will be the first thing to add!

Paulo

**Comment by ppeccin** [comment]
Hello guys!
I just started to work on the new version of Javatari, which will bring improvements like touch controls for mobile devices and much more, including this asked feature.

**Comment by BigEd** [comment]
That's great!

**Comment by estivalet** [comment]
@ppeccin way to go. Thanks! I really like your projects specially wmsx

**Comment by ppeccin** [comment]
Implemented on Release 4.0

**Comment by BigEd** [comment]
Excellent - thanks!

**Comment by ppeccin** [comment]
Check the docs to see how!

**Comment by BigEd** [comment]
Great - the example URLs are giving a 400 error - might that be fixable?

```
Could not load file: http://gamesarchive.org/Pitfall.rom
Error: 400 Bad Request
```

**Comment by ppeccin** [comment]
Those are just fictional examples only to illustrate the syntax. They do not point to real ROMs.

**Comment by BigEd** [comment]
Ah, I see! Might be worth switching to example.com, which is certain not to exist?

**Comment by ppeccin** [comment]
Nice idea! Thanks...
