### ISSUE TITLE
I try run on my ps4 but very low any button for adjust speed?

### ISSUE THREAD

**Issue by linuxfree2016** [ppeccin/javatari.js#11]
I try ps4 browser strange very low the emulation any button on control or can edit key in emulation config for change keys for adjust speed or Frames?

**Comment by ppeccin** [comment]
I don't know how good the PS4 web browser is, but maybe it is too slow to
run the emulator... It's Javascript VM is probably too slow.
It the browser cannot run the emulation at the correct speed, there is no
key that would make it run faster.

I would have to run more tests to verify this, but I don't have a PS4.

Paulo

**Comment by linuxfree2016** [comment]
thanks for reply i see in controls have the options for we change key for fire if possible try create one key for emulation where adjust speed frames there for can adjust with console controls.A lot of browsers now supporting html5 ps4 befor not but from firmware 6.50 support.
thanks

**Comment by ppeccin** [comment]
Yes, there are buttons assigned for FAST and SLOW emulation speed (left and
right shoulder triggers if I remember), but what I'm trying to explain is
that IF the browser is not fast enough to run the emulation, the FAST key
will not make it run faster, do you understand?
