### ISSUE TITLE
Javatari Configuration Doesn't Work

### ISSUE THREAD

**Issue by mallardgames** [ppeccin/javatari.js#12]
I am trying to embed configuration inside another javascript file:
[configuration](http://mallardgames.3b1.org/games/mallardseason/js/run.js)

However, no matter what I set it to, nothing works. However, if I use URL parameters it works fine which proves my path is fine:
[load via URL parameters](http://mallardgames.3b1.org/games/mallardseason/play.html?ROM=binaries/duckgame.bin)

both the configuration and URL parameters use the same exact path

> binaries/duckgame.bin

 Any ideas?

**Comment by ppeccin** [comment]
Hey!

For making configurations directly in JS, you should always place the code
AFTER you load the javatari.js file, and you must use the exact formal JS
variable for each parameter.

So this:
Javatari.ROM = "binaries/duckgame.bin";

Should be this:
Javatari.CARTRIDGE_URL  = "binaries/duckgame.bin";

The "ROM" shortcut is only valid for URL parameters. For setting via JS,
you must use the correct variable name.

Paulo

**Comment by mallardgames** [comment]
Thanks that seemed to fix it, but quote:

## Javatari Configuration and Launch Options

Several parameters are available for customizing the emulator. They can be changed either directly in Javascript if you are hosting the emulator in your own page, or via URL Query Parameters if you are creating links or bookmarks to open the emulator, or just using it in your browser.

All parameters are in the form of properties in the global object `Javatari`. Just set these object properties in Javascript, or use URL Query parameter/value pairs. For example:

```
Javatari.ROM = "files/Game.rom";      is the same as      https://javatari.org?ROM=files/Game.rom
```

**IMPORTANT:** Any parameter setting via Javascript must be done AFTER importing the `javatari.js` file.

I was using the example you gave in the [README.md](https://github.com/ppeccin/javatari.js/blob/master/README.md) file so you might want to change that so it is correct.

**Comment by ppeccin** [comment]
Yes, badly chosen example on the docs!
Thanks for pointing that out.

It will be fixed either way!

Paulo
