### ISSUE TITLE
[Request] Image loading and manipulation through JS

### ISSUE THREAD

**Issue by Leorivasc** [ppeccin/javatari.js#13]
Hi, 
The software is amazing, I tried to build a small website with it, but the only way I found to load and start games is through the URL in a new window or iframe. Is it possilble to add a feature such that the emulator could remain in the same page as the games list, and exchanging cartridge images without having to open a new page, maybe using click events? (sorry if the feature is already there, the doc doesn't mention or I didn't understand).
Thanks

**Comment by ppeccin** [comment]
Hi! Thanks for using Javatari!

Yes, there are some functions for that, but they are not official yet, and
not documented.
I will check in the code if the API is working as expected, and get back to
you soon.

Regards,
Paulo

**Comment by ppeccin** [comment]
Hi... Just checked the API.

You can achieve what you want (loading new ROMs dynamically) by calling the
File Loader method:


*Javatari.fileLoader.readFromURL(String url)*

The "url" parameter is relative to your current directory, so you can use
relative paths like for example:

*Javatari.fileLoader.readFromURL("mygames/Game.bin")*

Hope that works for you!

Paulo

**Comment by Zibri** [comment]
@ppeccin 
If the cartridge has already been loaded so it's stored in locastorage, how to load it from there (by javascript, not by the menu)?
