### ISSUE TITLE
Blurry pixels

### ISSUE THREAD

**Issue by BenMcLean** [ppeccin/javatari.js#2]
I've set up Javatari.js to run my demo [here](https://benmclean.github.io/Rebels-and-Redcoats-Atari2600/bin/) but I immediately notice that the pixels all look ugly and blurred. It seems to happen at any browser zoom level and on both Chrome and FireFox. This might be related to [Windows using GUI scaling](https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266(v=vs.85).aspx) as I'm not sure whether/how that affects Javascript.

This app should be using nearest neighbor scaling so the pixels look like absolutely sharp squares instead of being blurred around the edges.

**Comment by ppeccin** [comment]
Did you try ALT-T to toggle screen filtering? Isn't it working in your setup?
(please tell me your setup: machine, OS, browser, etc)

Nearest neighbor is not good for all applications, only when you have an exact multiple of the original scale. If not, you end up having pixels with different sizes on the screen. THAT looks ugly....  :-)

**Comment by BenMcLean** [comment]
Rows / columns of pixels of slightly different sizes (as long as it's consistent across the entire row/column) is much better than blurred pixels IMO.

My computer is an [ASUS Q551LN-BBI706 laptop](http://www.asus.com/supportonly/Q551LN/HelpDesk_Manual/) with a NVIDIA GeForce 840M graphics card running Windows 10 at 1080p resolution with 175% DPI scaling.

On Chrome, the CRT filter (Alt+T) has no effect. Nasty pixel blur happens whether it's on or off and the results look identical. On FireFox, turning the CRT filter off makes the pixels relatively sharper, but they still don't make absolutely sharp squares / rectangles like I think they should.

**Comment by ppeccin** [comment]
I think with Windows scaling ON maybe you will never see sharp pixels in
content rendered inside the browser, but I' not 100% sure.

I'll have to take a deeper look into this. Maybe something has changed in
Chrome and the "Filter OFF" option is not working correctly.

**Comment by BenMcLean** [comment]
> I think with Windows scaling ON maybe you will never see sharp pixels in
content rendered inside the browser, but I' not 100% sure.

Ah, well, I hope Microsoft, Google, Mozilla or whoever is responsible for that will fix it.

In the meantime, you might want to look at the CRT filter not turning off in Chrome.

**Comment by ppeccin** [comment]
Fixed. Chrome v55 changed a very small detail that was breaking this.
Please update to version 0.92
