### ISSUE TITLE
How to add key mapping?

### ISSUE THREAD

**Issue by Zibri** [ppeccin/javatari.js#34]
For example, I wish to add that the mous ONCLICK acts like FIRE button.
How can I do that?

**Comment by Zibri** [comment]
It seems I found how:

document.documentElement.onmousedown=()=>Javatari.room.consoleControls.keyDown(new KeyboardEvent('keypress',  {'keyCode':46}))

document.documentElement.onmouseup=()=>Javatari.room.consoleControls.keyUp(new KeyboardEvent('keypress',  {'keyCode':46}))

**Comment by ppeccin** [comment]
The more correct and complete way would be to create a new "Mouse" controller source for the emulator, in addition to the ones already present (Keys, Touch, Gamepad). With options, controls for turning it on-off, switch players (P1, P2) inputs, etc...

What you did could work as a quick-and-dirty workaround, but its not ideal.

**Comment by Zibri** [comment]
I guess so...

**Comment by Zibri** [comment]
What I am trying to do it to make it playable on an LG TV using the remote.
mousedown works but only for a few seconds becaus of how the tv remote is handled...
so I have to map a different key to FIRE... like RED/BLUE/GREEN/YELLOW keys on the remote or  a number key.

**Comment by ppeccin** [comment]
Interesting... But how are the remote buttons like RED/BLUE exposed to Javascript? Do they fire normal key events?
Or maybe you could pair a bluetooth controller to the TV, but I don't know if the TV browser would be able to detect and read it.

I'm not sure I understand when you say "How can I assign for example NUMBER 5 to fire?".
Did you look at the emulator settings screen? You can change all the controllers mappings for any keys that the emulator can detect. Is that working?

**Comment by Zibri** [comment]
> Interesting... But how are the remote buttons like RED/BLUE exposed to Javascript? Do they fire normal key events? Or maybe you could pair a bluetooth controller to the TV, but I don't know if the TV browser would be able to detect and read it.
> 
> I'm not sure I understand when you say "How can I assign for example NUMBER 5 to fire?". Did you look at the emulator settings screen? You can change all the controllers mappings for any keys that the emulator can detect. Is that working?

https://github.com/b-jesch/service.lgtv.remote/blob/master/KEYCODES.LG
