### ISSUE TITLE
"Invisible" Javatari?

### ISSUE THREAD

**Issue by Gamerzfanz21** [ppeccin/javatari.js#38]
Not sure if anyone still ventures on here, but I'm having a "invisible" issue when I load a URL from my website for the Javatari.  On my old site, everything works fine, but on my NEW site (different domain, same server), when I load the URL with any of the javatari games, it comes up blank, if I right click and view source, all the information is there, I can click links to the other files and they all seem to load fine (no 404 errors), there is a manifest file missing though?  I also upgraded from 4.0 to 5.0 but that didn't see to work.

I checked permissions from the old site with a new site and all are exactly the same, so I'm not sure what the issue is.

Any ideas what Im missing? (Im assuming all files needed are in the proper placement (as stated if you view source and click on file links they load )

**Comment by ppeccin** [comment]
Hi... Yes, still here!  :-)

What you mean by "blank"?
Did you check the browser's javascript console? Any errors?

Paulo

**Comment by Gamerzfanz21** [comment]
Javascript console doesn't show anything for it. 
(new site)
![vanguard](https://github.com/ppeccin/javatari.js/assets/22859500/acfd050b-08a6-4e0c-ba5d-30895028123c)

My image shows fine, but below that, should be the Javatari, but its just blank, I can give a direct link to the page itself if you need to see it.  But weirdly, it shows just fine on my other site. (both using Wordpress)

(old site)
![oldside_vanguard](https://github.com/ppeccin/javatari.js/assets/22859500/5f013839-fe2b-436b-8550-09e34e0efb95)

**Comment by ppeccin** [comment]
Yes please send a link to our page.

**Comment by ppeccin** [comment]
To your page I mean...

**Comment by Gamerzfanz21** [comment]
Here's a direct link: https://gamerzfanarcade.games/files/vanguard.html

**Comment by ppeccin** [comment]
Your script imports are wrong.

You should load only the main Javatari package (javatari.js) from the
release folder:
https://github.com/ppeccin/javatari.js/tree/master/release/stable/5.0/embedded

And follow the example on the index.html present on the same folder to
embed the emulator on your own page.

That's it. You import only ONE javascript file, and define the div tag
where you want the emulator to appear.

Peccin

**Comment by Gamerzfanz21** [comment]
Okay so I changed the url location of the javatari.js file in the code on the page and now it shows up, but now I get a 403 forbidden error message.

**Comment by Gamerzfanz21** [comment]
Nevermind, It was due to an htaccess file.  It's all working now.

**Comment by ppeccin** [comment]
Ok, glad it's working!

But you really should not be loading source files one by one. You should
use the official release file.

Peccin

**Comment by Gamerzfanz21** [comment]
#

> 

Im not sure what you mean by "single official release file" ?  Im using the 5.0 javatari.js file? (Its on my server).

**Comment by ppeccin** [comment]
Your page is loading dozens of script files, those are the source files.

You're also doing:
JAVATARI_IMAGES_PATH = "../src/runtime/images/files/";

That's wrong. You don't need that.

You should be loading ONLY ONE file: the release file (javatari.js) from
the folder I sent you.

The entire emulator to be embedded is on a single release file
(javatari.js).

Peccin

**Comment by Gamerzfanz21** [comment]
Ah okay, I removed everything but these

` </style>

        <script src="../src/main/room/screen/FullScreenSetup.js"></script>

    </head>

    <body>


        <script src="/release/stable/5.0/embedded/javatari.js"></script>

 

        <div id="javatari" style="text-align: center; margin: 2px auto 0;">

            <div id="javatari-screen" style="box-shadow: 2px 2px 10px rgba(0, 0, 0, .7);"></div>

        </div>

        <script>
            Javatari.AUTO_POWER_ON_DELAY = 0;
            Javatari.WEB_EXTENSIONS_SERVER = "webmsx.herokuapp.com";
            Javatari.CARTRIDGE_URL = "*************";
        </script>

    </body>
`

**Comment by ppeccin** [comment]
As per the provided example html file for embedding, the only thing you
need is this:

<script src="/release/stable/5.0/embedded/javatari.js"></script>

<div id="javatari" style="text-align: center; margin: 2px auto 0;">

      <div id="javatari-screen" style="box-shadow: 2px 2px 10px rgba(0, 0,
0, .7);"></div>

</div>


And also, if you need to load a ROM via JS:

Javatari.CARTRIDGE_URL = "*************";


Everything else is wrong and can cause problems.


Peccin

**Comment by Gamerzfanz21** [comment]
Okay, I removed all those extras, other than what I need including the cartridge_url.  Its an arcade website.  So all should be good now.  Thanks for all your help.

**Comment by ppeccin** [comment]
You're welcome!
