### ISSUE TITLE
how to save state and score

### ISSUE THREAD

**Issue by mohsenghaderi** [ppeccin/javatari.js#5]
is it possible to save state or get player score at the end of the game?

**Comment by ppeccin** [comment]
Hi,

For the Savesate yes, you can make one at any time.

However, for the "score" and "end of the game", there is no such thing from the emulators perspective. It cannot tell when the game ends, or where to get the score from. There are games that even don't have scores, or don't "end" in a clear way.

You will have to know the specific memory location where the score is held for each specific game, and also a means to tell if the game has ended, only by observing the machine's memory.

Paulo

**Comment by ppeccin** [comment]
Closing
