### ISSUE TITLE
Screen Capture Not Working

### ISSUE THREAD

**Issue by techana** [ppeccin/javatari.js#9]
I tried taking screen captures (screenshots) for running games, but the Alt+G keyboard shortcut does not work. I tried it in macOS (Chrome & Safari) and in Windows (Chrome) and the same result.

**Comment by ppeccin** [comment]
Screen Capture key is wrong in the Help Screen. It will be fixed, thanks.
The correct key in current release is ALT-X.

Paulo

**Comment by ppeccin** [comment]
Fixed. ALT-G is now working.
